### ISSUE TITLE
changing password with MySQL install doesn't work

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#47] opened 2015-03-18 01:03 UTC
Create user passtest with password "ancien".
Check hashes:
MySQL user: "*E0CF25CC276C9C10B4CC7D246CBC8C81C5577A34"
FMF user: "fEHBzCC2Ufg/7dc3+dUVS9ijHRI="

Login with passtest/ancien
-> Open usermanager
-> change password (type old pass once & new pass "nouveau" twice) and type ok:
check hashes: nothing changed **first bug**
-> click icon save user
check hashes:
MySQL user: **second bug** unchanged "*E0CF25CC276C9C10B4CC7D246CBC8C81C5577A34"
FMF user: changed "yv5fEdajsm5Z8oRU0K2QqVHGSmo="
-> close usermanager
check hashes:
MySQL user: unchanged "*E0CF25CC276C9C10B4CC7D246CBC8C81C5577A34"
FMF user: changed "yv5fEdajsm5Z8oRU0K2QqVHGSmo="
close app
login with passtest / nouveau : "incorrect login password information"
(cannot connect to MySQL with new password, MySQL user table still has the old one)

>"UserBase                  ** ERROR(userbase.cpp:481) ** Unable to connect to the MySQL
>                          server, with user passtest" 
>"UserBase                  ** ERROR(userbase.cpp:482) **  " 
>"Warning Dialog            You can try 2 more time(s)."

try to login with passtest / ancien:

>checkLogin "passtest" "ancien" 
>"UserBase                  Database server identifiers are correct for login passtest: 6" 
>"UserBase                  Connected to database 'fmf_users' with driver 'QMYSQL@fmf_users'" 
>"SELECT `USERS`.`USER_UUID`, `USERS`.`LOGIN`, `USERS`.`PASSWORD` FROM `USERS` WHERE  (`USERS`.`LOGIN` ='cGFzc3Rlc3Q=')" 
>"Warning Dialog            You can try 3 more time(s)."

**Comment by jeromecc** [comment] 2015-03-18 01:13
If you manually change password hash to *F29E0817A101614AB37A5EC083A5450C45C4282A (MySQL password hash for "nouveau") for password column inside user table of mysql database, login with passtest / nouveau is ok.

**Comment by jeromecc** [comment] 2015-03-21 13:20
Possible cause of bug:
in userbase.cpp
Update of MySQL server password for current user not coded in function:
bool UserBase::saveUser(UserData *user)
called when saving changes made in usermanager ui                                       
see comment on line 1224:
// TODO: update identifiers according to the driver.

**Comment by EricMaeker** [comment] 2015-03-22 17:37
Humm, the problem is that the defaultuserviewerpage give the crypted password to the IdentityWidget. Then when the password changes, only the crypted is modified in the UserModel. But if you look at UserModel
UserModel 966 setData -> calls UserBase::changeUserPassword
UserModel 971 setData -> setting cryptedPassword -> no changes in driver

We need to catch the clearpassword when the user changes its password.

This bug is inside the spaghetti between DefaultUserContactWidget -(use)-> IdentityWidget -(get/setData)-> PasswordDialog and Widget -get/setData-> IdentityWidget  -> DefaultUserContactWidget -> UserModel -> UserBase

**Comment by jeromecc** [comment] 2015-03-27 19:24
Yep. I've been trying to disentangle those spaghettis for days and nights. Mixing password creation during user creation and password change (both using the same dialog with hidden fields) is clever but it's too clever for me! I'm tempted to clearly separate password change, with a new icon in usermanager main window.
Writing a separate password change dialog and separate code would probably be quicker and neater than retracing what the clever original writer had in mind. :-)
@EricMaeker, give me your 2 cents about it.
If you can quickly hack a temporary fix, that's ok for me too. This is the last bug delaying the 0.9.6 release our users are eagerly waiting for... :-)

Thanks.

**Comment by EricMaeker** [comment] 2015-03-28 19:21
Or will ne easier To keep code as it is than rewrite new pieces that
already exist...
I ll try to fix this

Éric

**Comment by jeromecc** [comment] 2015-04-07 13:52
It doesn't seem easier after all... I'll try to fix "code as it is" until the end of the week, then I'll implement another solution. If it takes three weeks to fix a release critical bug, it probably means that going on with "code as it is" is not the best option. ;-)

**Comment by EricMaeker** [comment] 2015-04-11 08:06
Working on this issue today

Eric

**Comment by jeromecc** [comment] 2015-04-12 22:02
@EricMaeker, thank you very much for your work on the patch. :-) You did 90% of the work!

We're almost there, but not yet.

Changing password for fmf_admin doesn't work because it doesn't have the UPDATE privilege for mysql database.

It doesn't work either for regular users:
Changing password password for regular users bring this MySQL error:

> "Database ** ERROR(database.cpp:617) ** SQL Error: 
                               * QMYSQL: Unable to execute query
                               * UPDATE command denied to user
                          'heloise'@'localhost' for table 'user'
                               * UPDATE `mysql`.`user` SET `Password` = PASSWORD('nouveau') WHERE `User` = 'heloise';" 

Normal users or normal admins (newly created admins) don't have UPDATE privilege on database mysql. Maybe admins should have UPDATE privilege, but normal user must not have UPDATE privilege or any privilege on mysql database.
Solution: add UPDATE privilege for superadmin and admins
Use MySQL command SET PASSWORD for normal users.

I'll try to fix this ASAP.
Thanks again to Eric for doing the hard part and making it easier for me to help with basic debugging. ;-)

**Comment by jeromecc** [comment] 2015-04-12 22:40
Testing password change for superuser fmf_admin
With UPDATE privilege on mysql.*, it still doesn't work.

I checked fmf_admin password in mysql.user: the password is changed.
I checked fmf_admin password in fmf_user database: the password is NOT changed.

Probably a regression coming from the patch.

**Comment by EricMaeker** [comment] 2015-04-13 06:23
Le 13/04/2015 00:40, jeromecc a écrit :
> Testing password change for superuser fmf_admin
> With UPDATE privilege on mysql.*, it still doesn't work.
> 
> I checked fmf_admin password in mysql.user: the password is changed.
> I checked fmf_admin password in fmf_user database: the password is NOT
> changed.
> 
> Probably a regression coming from the patch.

I didn't made any changes inside Database and/or UserBase. But I'll
check this.
We can use SET PASSWORD instead of changing the mysql.user table.

	https://dev.mysql.com/doc/refman/5.5/en/set-password.html

Eric

**Comment by EricMaeker** [comment] 2015-04-13 06:29
> We can use SET PASSWORD instead of changing the mysql.user table.
> 
> 	https://dev.mysql.com/doc/refman/5.5/en/set-password.html

This function will be deprecated in 5.7

	https://dev.mysql.com/doc/refman/5.7/en/alter-user.html

One more problem to manage... MySQL version.
Eric

**Comment by jeromecc** [comment] 2015-04-13 15:38
#SET PASSWORD deprecation
MySQL versions support: have a look at this: http://en.wikipedia.org/wiki/MySQL#Versions

MySQL server versions 5.0 & 5.1 were supported for 8 years. Current officially recommended version, 5.6, was launched on 2011. 5.7 was launched in 2013. So SET PASSWORD (FOR) will be supported at least until 2021. I don't think we should worry to much about this. :-)

#MySQL version management
I suggest we stick to Debian Stable version. Current Debian Stable (Wheezy) and upcoming Debian Stable (Jessie) both use MySQL server 5.5, so we're ok for at least the next two years.
If you're ok about this, I will add a notice on the Download page that clearly states that we support MySQL 5.5 which should be support at least until 2018 and is available for download on Oracle website for all platforms. Once again, let's not worry about this. ;-)
Just to let you know: I tested running current FMF code on MySQL 5.6 and everything seemed just fine. Oracle will never remove backward compatibility from version 5.X to version 5.X+1 so we can relax. I guess MySQL features are much more stable in time than Metero.js features. ;-)

#changing MySQL password
If a normal user wants to update her password, we must use SET PASSWORD (it should also work for an admin user wanting to change her own password).
If an admin user wants to change another user's password, we can use SET PASSWORD FOR or the current way:
> ("UPDATE `mysql`.`user` SET `Password` = PASSWORD('%1') WHERE `User` = '%2';")

My suggestion:
Database::changeMySQLUserPassword() will use SET PASSWORD
introduce a new function
Database::changeMySQLAdminPassword() will use UPDATE... so that it can change the current user password or any other user password.

In /usermanagerplugin/database/userbase.cpp is there a way to test if current user is admin, so that UserBase::changeUserPassword() knows which function to call?
Maybe with 
if (user->hasRight(Constants::USER_ROLE_USERMANAGER, Core::IUser::AllRights))
   Database::changeMySQLAdminPassword()
else
    Database::changeMySQLUserPassword()
?

**Comment by jeromecc** [comment] 2015-04-15 01:39
I added UPDATE privilege on the whole mysql database for fmf_admin in the sql script. Having UPDATE privilege only on user table (mysql.user) was not enough to be able to change other users passwords (with SET PASSWORD FOR or with UPDATE).
To be able to create new admins which can change other users password, fmf_admin or other admins need GRANT OPTION. I added this too.

**Comment by jeromecc** [comment] 2015-04-21 13:51
It still doesn't work.
I can't connect after changing fmf_admin password from "fmf_admin" to "nouveau" on a fresh install...
:-(

 "UserBase                  Check user login fmf_admin: *******" 
 "nouveau" "yv5fEdajsm5Z8oRU0K2QqVHGSmo=" 
 "UserBase                  ** ERROR(userbase.cpp:488) ** Unable to connect to the MySQL
                          server, with user fmf_admin" 
 "UserBase                  ** ERROR(userbase.cpp:489) ** Driver not loaded Driver not loaded" 
 "Warning Dialog            You can try 2 more time(s)."

**Comment by EricMaeker** [comment] 2015-04-23 06:26
Hi,

I've checked on my configuration and password modification works
perfectly when changing own password. I've committed small improvements
and one bug correction (with user isModified status). Can please recheck
own modification and then SU changing other user password.

Also, I didn't user creation. We should check that the user password is
correctly set on the server and the database. I'll make some tests ASAP.

Eric

**Comment by jeromecc** [comment] 2015-05-05 22:43
Just compiled FMF with Qt5 on Debian 8.0 Stable: on a completely fresh install, changing fmf_admin password works! :-D
BUT: if fmf_admin user was set up on Qt4, changing this same fmf_admin user password on Qt5 doesn't work: "old password is incorrect" even though it's fmf_admin
I guess it comes from the different hashing method between Qt4 and Qt5.
We should address this issue before releasing FMF 0.9.6 or our users will experience problems changing their passwords after the upgrade.
I tested again and again and again with Qt4, it doesn't work, but we don't care because FMF is based on QT5 for all platforms now.

**Comment by EricMaeker** [comment] 2015-05-06 06:21
Le 06/05/2015 00:43, jeromecc a écrit :
> Just compiled FMF with Qt5 on Debian 8.0 Stable: on a completely fresh
> install, changing fmf_admin password works! :-D
> BUT: if fmf_admin user was set up on Qt4, changing this same fmf_admin
> user password on Qt5 doesn't work: "old password is incorrect" even
> though it's fmf_admin

FMF can be upgraded from Qt4 to Qt5 without any password problem. But it
can not be downgraded from Qt4 to Qt5 ! There are no possibilities to
improve this fact.

We can run more tests on password when upgrading from Qt4 to Qt5. There
are unit tests also.

> I tested again and again and again with Qt4, it doesn't work, but we
> don't care because FMF is based on QT5 for all platforms now.

I was coding using Qt4 and did not experiment any problem. Did the
password created with a Qt4 version?

-- 
Eric

**Comment by jeromecc** [comment] 2015-05-07 21:44
"FMF can be upgraded from Qt4 to Qt5 without any password problem."
On my computer, I installed FMF on MySQL with Qt4.
Then I tried to access the database with FMF compiled with Qt5.
It's working, FMF Qt5 can deal with FMF databases and users created with FMF Qt4.
BUT, as I tried to change fmf_admin password, FMF Qt5 said there was an error with the old password (which is fmf_admin).
So we cannot say that the upgrade is without any password problem because it appears that if our users upgrade, they won't be able to change their old passwords to new ones, ever. That's a serious problem, because good practices about password policy suggest that changing passwords once in a while is increasing security.
It's the last serious glitch that prevents building FMF 0.9.6 for all platforms.
We're almost there! ;-)
Thanks for your help Eric. As soon as this is fixed, I'll do all the building work for all platforms. :-)

**Comment by jeromecc** [comment] 2015-05-13 15:05
Changing a password created on FMF Qt4 with FMF Qt5 doesn't work because new hash (sha3-512:) created during first run with Qt5 is not recorded in the database.
Before:
(2, '1d011f5dd3f14b9faf8e5d3dde767bc8', 1, 0, 'amVyb21l','cjFWZQxXeNDk30svv+76ZTWTAuU=','2015-05-13', 'JEROME', 'JEROME','Jerome', 0, 0, '', 'en', 0);

Console:
"UserBase                  Check user login jerome: ******"
"jerome"
"sha3-512:vm/jp4/2kw+TnW7WxPWA8vo+Z6elV3ZJo6YM4YISyu1uNUy9eqNXEnFOBHYDI/166P6/bo2FNX1vMBGAvL7FvQ=="
"UserBase                  Database server identifiers are correct for
login jerome: ******"
"UserBase                  Connected to database 'fmf_users' with driver
'QMYSQL@fmf_users'"
"SELECT `USERS`.`USER_UUID`, `USERS`.`LOGIN`, `USERS`.`PASSWORD` FROM
`USERS` WHERE  (`USERS`.`LOGIN` ='amVyb21l')"
"jerome" "cjFWZQxXeNDk30svv+76ZTWTAuU="
"sha3-512:vm/jp4/2kw+TnW7WxPWA8vo+Z6elV3ZJo6YM4YISyu1uNUy9eqNXEnFOBHYDI/166P6/bo2FNX1vMBGAvL7FvQ=="
"UserIdentifier            User can be identified."
bool UserPlugin::UserModel::setCurrentUser(const QString&, const
QString&, bool, bool) "jerome"
"UserModel                 Setting current user uuid to
1d011f5dd3f14b9faf8e5d3dde767bc8"
"UserBase                  User 1d011f5dd3f14b9faf8e5d3dde767bc8
successfully updated."
"UserBase                  Connected to database 'fmf_users' with driver
'QMYSQL@fmf_users'"
"UserModel                 Connected as
                             JEROME JEROME Jerome"
After:
(2, '1d011f5dd3f14b9faf8e5d3dde767bc8', 1, 0, 'amVyb21l',
'cjFWZQxXeNDk30svv+76ZTWTAuU=', '2015-05-13', 'JEROME', 'JEROME',
'Jerome', 0, 0, '', 'en', 0);

Hash is the same old hash.

**Comment by jeromecc** [comment] 2015-05-14 23:30
## Changin own MySQL password was buggy:
### First problem:
A connected MySQL user can change her/his own password, but we have to use SET PASSWORD = ('newpassword)';
I corrected this in the source code.
Related future problem: if the host on which the MySQL server is running changes, the user will not be able to connect. SET PASSWOD cannot include a host as an arguement.
IMHO this is a hard limit of our current user management system. If the host change, it will be the job of the sysadmin to create new entries in the mysql / user table (copy pasting the hash etc). We could write a SQL script to do that if requested.

### Second problem:
FLUSH PRIVILEGES requires RELOAD privilege and is not necessary with the SET PASSWORD command. See MySQL documentation [When Privilege Changes Take Effect](https://dev.mysql.com/doc/refman/5.5/en/privilege-changes.html)
So we had a MySQL privilege error message and the password change was reversed.
So I simply removed the FLUSH PRIVILEGE block in libs/utils/database.cpp in function Database::changeMySQLUserOwnPassword()

Now I think everything works with Qt4. :-)

We still have to figure out a fix for Qt4->Qt5 update.

**Comment by EricMaeker** [comment] 2015-05-17 18:56
Updated in commit
https://github.com/FreeMedForms/freemedforms/commit/83c5ff4da6603c80d2469a617c3749fb937bc481

**Comment by jeromecc** [comment] 2015-05-18 20:04
Dr Eric Maeker just solved all problems with password on both Qt4 and Qt5 versions! Changing one's own password works on both versions, changing another user's password with an admin works on both versions, password update from Qt4 to Qt5 works perfectly.

Thank you very much Eric! :-D

**Comment by nflqt** [comment] 2015-05-19 07:54
jeromecc <notifications@github.com> writes:

> Dr Eric Maeker just solved all problems with password on both Qt4 and
> Qt5 versions! Changing one's own password works on both versions,
> changing another user's password with an admin works on both versions,
> password update from Qt4 to Qt5 works perfectly.

Wonderfull!

>
> Thank you very much Eric! :-D

Thank you Éric! And thank you too Jérôme! ^^

-- 
Nicolas Floquet
www.pharmanerd.flqt.fr | www.logibaba.flqt.fr | www.librehealthcare.org
5, impasse du bois 61450 La Ferrière-aux-Étangs, Normandie, France
06 32 93 03 51
Mail rédigé et signé avec des logiciels libres
PGP : 8CB0 FE5C 27BB A86E 0B6B  1DEA AB88 CF5B 9200 CDB6

**Comment by jeromecc** [comment] 2015-05-21 23:29
On 05/19/2015 09:54 AM, Nicolas Floquet wrote:
> jeromecc <notifications@github.com> writes:
>
> > Dr Eric Maeker just solved all problems with password on both Qt4 and
> > Qt5 versions! Changing one's own password works on both versions,
> > changing another user's password with an admin works on both versions,
> > password update from Qt4 to Qt5 works perfectly.
>
> Wonderfull!
>
> >
> > Thank you very much Eric! :-D
>
> Thank you Éric! And thank you too Jérôme! ^^
Nicolas could you try to compile the current source on Manjaro and/or Arch?

git clone git@github.com:FreeMedForms/freemedforms.git
cd freemedforms
qmake freemedforms.pro -r "CONFIG+=debug debug_without_install"
make
./bin/freemedforms/freemedforms_Qt5_linux-gpp-64/freemedforms_debug

It's all that it take! ;-)

It there are libraries or packages missing the complete list is on
https://freemedforms.com/en/code/buildsystem

Thanks.

**Comment by nflqt** [comment] 2015-06-09 15:06
jeromecc <notifications@github.com> writes:

> git clone git@github.com:FreeMedForms/freemedforms.git
> cd freemedforms
> qmake freemedforms.pro -r "CONFIG+=debug debug_without_install"
> make
> ./bin/freemedforms/freemedforms_Qt5_linux-gpp-64/freemedforms_debug
>
> It's all that it take! ;-)

J'ai obtenu cette erreur à la commande make. 

Error FODC0002 in file:///home/nico/install/git/freemedforms/plugins/padtoolsplugin/PadTools.pluginspec: Error opening /home/nico/install/git/freemedforms/plugins/padtoolsplugin/PadTools.pluginspec: No such file or directory
Makefile:623 : la recette pour la cible « PadTools.json » a échouée
make[3]: *** [PadTools.json] Erreur 2
make[3] : on quitte le répertoire « /home/nico/install/git/freemedforms/plugins/padtoolsplugin »
Makefile:711 : la recette pour la cible « sub-------plugins-padtoolsplugin-make_first » a échouée
make[2]: *** [sub-------plugins-padtoolsplugin-make_first] Erreur 2
make[2] : on quitte le répertoire « /home/nico/install/git/freemedforms/freemedforms/plugins »
Makefile:131 : la recette pour la cible « sub-plugins-make_first-ordered » a échouée
make[1]: *** [sub-plugins-make_first-ordered] Erreur 2
make[1] : on quitte le répertoire « /home/nico/install/git/freemedforms/freemedforms »
Makefile:42 : la recette pour la cible « sub-freemedforms-make_first » a échouée
make: *** [sub-freemedforms-make_first] Erreur 2


Je vais essayer de recompiler à partir du paquet AUR.

-- 
Nicolas Floquet
www.pharmanerd.flqt.fr | www.logibaba.flqt.fr | www.librehealthcare.org
5, impasse du bois 61450 La Ferrière-aux-Étangs, Normandie, France
06 32 93 03 51
Mail rédigé et signé avec des logiciels libres
PGP : 8CB0 FE5C 27BB A86E 0B6B  1DEA AB88 CF5B 9200 CDB6

**Comment by jeromecc** [comment] 2015-06-09 15:32
Thank you very much for this bug report. We need bug reports to help us improve our project. :) We need people building FMF apps on Arch Linux! Please keep on trying to build from source. The AUR package is known to work well but it is not up to date. We need to know if our current master source code is working for your OS.

A few remarks about issue reporting:
 * English is mandatory :)
 * Having a GNU/Linux system that speaks English is a major help for everyone. Only french speaking persons will be able to understand the errors your console is reporting if your system locales are in french. Could you install english locales and temporarily switch your system to english for compiling? It is NOT mandatory but it would be better. ;)
 * You need to tell us 4 things
    1. Operating System? Precise version of OS? OS updated before compilation?
    2. precise version of source (master in your case I guess) type git status
    3. precise version of Qt; type this and send us the result please
qmake -v

Thank you very much for helping us provide an application that can be built on all GNU/Linux flavours! :)
The file should be
Padtools.pluginspec
not
PadTools.pluginspec

Could you git clone again somewhere else and start the build again from fresh please?

**Comment by jeromecc** [comment] 2015-06-09 15:34
Look at this issue: https://github.com/FreeMedForms/freemedforms/issues/48
It is a good idea to search past issues on the site. :-)
It seems my fix has been reversed.

**Comment by jeromecc** [comment] 2015-06-09 16:22
In fact my fix was buggy! This should work now. Please git clone again and try to build. :-) Thank you.

Last remark: please open another issue next time because it has nothing to do with issue #47 :-p

**Comment by EricMaeker** [comment] 2015-06-09 18:01
Please see #48 I provide all explanations to fix both issues

**Closed** 2015-07-21 13:42 UTC
Labels: bug

**Comment by mcarassale** [comment] 2016-10-25 14:35
Hi All,

has the issue of changing password and user creation been fixed?
i have just installed the software and it doesnt look like i can create any new users or change the Admin user/password.

thanks

**Comment by jeromecc** [comment] 2016-10-25 16:59
Hi!
It has been fixed since version 0.9.6. https://github.com/FreeMedForms/freemedforms/releases/tag/v0.9.8
If you say which version you are using, it could help.

**Comment by mcarassale** [comment] 2016-10-28 10:26
thanks,, i have installed the later version and it is fixed now.

would you know if there is support for Italian language?



________________________________

**Comment by mcarassale** [comment] 2016-10-28 14:03
Hi,


i was wondering if the program can be customized?

basically i would like to add 2 new entries in the Form editor, is this possible?




________________________________

**Comment by EricMaeker** [comment] 2016-10-29 11:58
Hi,
Yes the forms are fully customizable. The french non-profit association
gets a full documentation to help you to add new items and create new
forms from scratch. There is also a full documentation if you want to
create a new editors (like line editor, date editor).

https://freemedforms.com/fr/asso/start

Thanks for your report
Eric

**Comment by mcarassale** [comment] 2016-10-29 19:34
Thank you Eric.

Do i need to join the comunity in order to ask for help?
Sorry i dont understand French, so is a bit of a problem for me :-(



Sent from my BlackBerry — the most secure mobile device
